/*
 * dpapi_backup_key_recovery.c
 *
 * Windows DPAPI domain-backup-key recovery path. Every
 * domain-joined Windows machine encrypts DPAPI master keys
 * (which protect browser passwords, Wi-Fi credentials,
 * BitLocker recovery keys, Credential Manager entries,
 * certificate private keys) under the domain's DPAPI backup
 * key pair. That pair is RSA-2048, stored in the NTDS.dit
 * on every domain controller, and NEVER rotated by default.
 *
 * An attacker who factors this RSA-2048 key retroactively
 * decrypts every DPAPI-protected secret that was ever
 * generated by any domain member, across the full history
 * of the AD forest.
 *
 * Published by Benjamin Delpy (Mimikatz), harmj0y (SharpDPAPI).
 */

#include <stdint.h>
#include <string.h>
#include "dpapi.h"

/* DPAPI master-key blob, stored per-user in:
 *   %APPDATA%\Microsoft\Protect\<SID>\<GUID>
 *
 * The "domain key" section of the master key blob is the
 * RSA-OAEP-encrypted copy of the master key that allows
 * domain-admin / backup recovery. */
struct dpapi_mk_blob {
    uint32_t  version;            /* always 2                    */
    uint8_t   guid[16];          /* identifies this master key  */
    uint32_t  flags;
    uint8_t   salt[16];
    uint32_t  pbkdf2_iterations;
    uint32_t  alg_id;            /* CALG_3DES / CALG_AES_256    */
    uint32_t  hash_alg;          /* CALG_HMAC / CALG_SHA_512    */
    uint8_t   encrypted_mk[64];  /* PBKDF2-wrapped mk for user  */
    /* ---- domain backup section ---- */
    uint32_t  domain_key_version;
    uint8_t   domain_key_iv[16];
    uint8_t   domain_encrypted_mk[256]; /* RSA-OAEP(mk, backup_pk) */
};

/* On a domain controller, the backup RSA key pair is stored
 * in NTDS.dit under:
 *   CN=BCKUPKEY_<GUID>,CN=System,DC=...
 * as an attribute of type ms-BKRP-BackupKey. The private key
 * is stored in cleartext(!) inside the attribute — it's meant
 * to be accessible to any domain controller, since DPAPI
 * backup-recovery is a DC service (MS-BKRP protocol). */
struct dpapi_domain_backup_key {
    uint32_t  version;           /* 1 = RSA                     */
    uint32_t  key_len;           /* 2048 / 8 = 256              */
    uint8_t   private_key[256];  /* RSA private exponent d      */
    uint8_t   public_key[256];   /* RSA modulus n                */
    uint8_t   exponent[4];       /* 65537                       */
};

/* Recovery: the DC uses RSA-OAEP decrypt to recover the mk
 * from domain_encrypted_mk, then re-wraps under the user's
 * password to return to the user via MS-BKRP. */
int dpapi_recover_mk(const struct dpapi_mk_blob *blob,
                      const struct dpapi_domain_backup_key *bk,
                      uint8_t *mk_out, size_t mk_out_len)
{
    return rsa_oaep_decrypt(
        bk->private_key, bk->key_len / 8,
        bk->public_key, bk->key_len / 8,
        bk->exponent, 4,
        blob->domain_encrypted_mk, 256,
        mk_out, &mk_out_len);
}

/* =========================================================
 *  What DPAPI master keys protect:
 * ========================================================= */

struct dpapi_consumer {
    const char *subsystem;
    const char *data_type;
    const char *risk;
};

static const struct dpapi_consumer consumers[] = {
    { "Chrome/Edge",   "saved passwords",
      "every domain user's browser credentials" },
    { "Credential Manager", "Windows Vault entries",
      "RDP, SMB, generic credentials" },
    { "Wi-Fi",         "WPA2/WPA3 PSKs",
      "every SSID profile on domain-joined laptops" },
    { "Certificate Store", "private keys for S/MIME, code-sign",
      "retroactive email decrypt + forgery" },
    { "BitLocker",     "recovery key protectors",
      "full-disk decryption of every domain-joined drive" },
    { "EFS",           "file encryption keys",
      "encrypted file shares + roaming profiles" },
    { "RDP",           "RemoteApp SSO blobs",
      "session tokens to jump-hosts" },
    { "Scheduled Tasks","run-as credentials",
      "service accounts with elevated privileges" },
};

/* ---- Attack once domain backup key RSA is factored --------
 *  1. Retrieve the domain backup key from NTDS.dit (any DC
 *     backup, DVSL snapshot, or ntdsutil offline extract).
 *     The public key (modulus n) is sufficient input to the
 *     factoring algorithm.
 *  2. Collect DPAPI master-key blobs from any domain-joined
 *     machine (user-profile backup, SCCM/Intune cache, or
 *     offline disk image).
 *  3. RSA-OAEP decrypt every blob's domain_encrypted_mk.
 *  4. Use the recovered master key to DPAPI-decrypt every
 *     consumer listed above.
 *  Outcome: retroactive plaintext of every browser password,
 *  BitLocker key, S/MIME key, credential vault entry, and EFS
 *  key ever generated in that AD forest. Forest-wide.
 *
 *  Recovery: Microsoft has no rotation mechanism for the domain
 *  backup key. Manual: create a new backup key, but ALL existing
 *  master-key blobs remain encrypted under the OLD key.
 *  Re-encrypting them requires every user to log in and trigger
 *  a master-key regeneration — in a 50k-seat enterprise this is
 *  a year-long project. Meanwhile the old key remains valid.
 * --------------------------------------------------------- */
