// Source: Kubernetes - https://github.com/kubernetes/kubernetes
// File:   cmd/kubeadm/app/util/pkiutil/pki_helpers.go
// License: Apache-2.0
//
// Relevant excerpt: RSA-2048 is the default key type for all cluster
// CA certificates generated by kubeadm.
//
// Every kubeadm-bootstrapped Kubernetes cluster has:
//   - A cluster CA (RSA-2048 by default)
//   - An etcd CA (RSA-2048 by default)
//   - A front-proxy CA (RSA-2048 by default)
//   - Service account signing keys (RSA-2048 by default)
//
// These certs have 10-year validity by default.  A cluster created
// today will have its CA certs expire in 2034 - potentially after
// a CRQC exists.  kubeadm 1.33+ supports hybrid key exchange in TLS
// (via Go 1.24 ML-KEM) but certificate *signatures* require Go 1.26
// ML-DSA support, which is not yet available.  The CA is still RSA.

package pkiutil

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"

	kubeadmapi "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm"
)

// rsaKeySizeFromAlgorithmType maps the kubeadm API enum to a bit count.
// The empty string ("") maps to RSA-2048 - this is the default when no
// --certificate-key-algorithm flag is passed, which is almost always.
func rsaKeySizeFromAlgorithmType(keyType kubeadmapi.EncryptionAlgorithmType) int {
	switch keyType {
	case kubeadmapi.EncryptionAlgorithmRSA2048, "": // "" == unset == default
		return 2048
	case kubeadmapi.EncryptionAlgorithmRSA3072:
		return 3072
	case kubeadmapi.EncryptionAlgorithmRSA4096:
		return 4096
	default:
		return 0 // unknown RSA size; caller will error
	}
}

// GeneratePrivateKey is the single entry point for all kubeadm cert generation.
// ECDSA P-256/P-384 are available but not the default.
// No ML-DSA (Dilithium) option exists - Go stdlib doesn't support it yet.
// RSA-2048 is what every cluster gets unless the operator explicitly opts out.
func GeneratePrivateKey(keyType kubeadmapi.EncryptionAlgorithmType) (crypto.Signer, error) {
	switch keyType {
	case kubeadmapi.EncryptionAlgorithmECDSAP256:
		return ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	case kubeadmapi.EncryptionAlgorithmECDSAP384:
		return ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
	}

	rsaKeySize := rsaKeySizeFromAlgorithmType(keyType)
	if rsaKeySize == 0 {
		return nil, errors.Errorf("cannot obtain key size from unknown RSA algorithm: %q", keyType)
	}
	// Default path: rsa.GenerateKey with 2048-bit key
	return rsa.GenerateKey(rand.Reader, rsaKeySize)
}

// NewPrivateKey is the function variable used throughout kubeadm phases.
// Replacing this with a PQC generator is blocked until:
//   1. Go stdlib adds ML-DSA (targeted for Go 1.26, ~late 2026)
//   2. x/crypto/x509 supports ML-DSA certificate signing
//   3. All Kubernetes control plane components (kube-apiserver, etcd,
//      kubelet) can validate ML-DSA signatures in TLS client certs
var NewPrivateKey = GeneratePrivateKey
